// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: blob.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlobClient is the client API for Blob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlobClient interface {
	Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type blobClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobClient(cc grpc.ClientConnInterface) BlobClient {
	return &blobClient{cc}
}

func (c *blobClient) Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.Blob/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobServer is the server API for Blob service.
// All implementations must embed UnimplementedBlobServer
// for forward compatibility
type BlobServer interface {
	Send(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBlobServer()
}

// UnimplementedBlobServer must be embedded to have forward compatible implementations.
type UnimplementedBlobServer struct {
}

func (UnimplementedBlobServer) Send(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedBlobServer) mustEmbedUnimplementedBlobServer() {}

// UnsafeBlobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobServer will
// result in compilation errors.
type UnsafeBlobServer interface {
	mustEmbedUnimplementedBlobServer()
}

func RegisterBlobServer(s grpc.ServiceRegistrar, srv BlobServer) {
	s.RegisterService(&Blob_ServiceDesc, srv)
}

func _Blob_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Blob/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServer).Send(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Blob_ServiceDesc is the grpc.ServiceDesc for Blob service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blob_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Blob",
	HandlerType: (*BlobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Blob_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blob.proto",
}
